server:
  port: ${PORT:3001}

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/data?useSSL=false
    password: root
    username: root
    dbcp2:
      validation-query: select 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update